# Site settings
title: Matthias Balke
description: 'Kitesurfer. Photographer. Developer.'
url: 'https://www.matthias-balke.de'
baseurl: ''
cover: car_bg.jpg
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

blog: false
feed: false

author:
  name: 'Matthias Balke'
  email: 
  twitter_username: 3lt0n
  facebook_username: 
  github_username:  matthiasbalke
  linkedin_username:  matthiasbalke
  eyeem_username: matthiasbalke

collections:
  posts:
    output: false

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
